### ISSUE TITLE
Implementation for Privacy lock and tamper alert feature

### ISSUE THREAD

**Issue by ashinasok** [ttlock/iOS_SDK_Demo#10]
Hi ,

I am currently using TTLock SDK wherein I need to implement privacy lock and tamper alert feature . The implementation include setting and getting the corresponding values of these features from the lock.

Please guide .
Thanks

**Comment by JuannyiOS** [comment]
Hi , use those two methods



 
+ (void)setLockConfigWithType:(TTLockConfigType)type
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; on:(BOOL)on
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; lockData:(NSString *)lockData
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; success:(TTSucceedBlock)success
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; failure:(TTFailedBlock)failure;
 


 
+ (void)getLockConfigWithType:(TTLockConfigType)type
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; lockData:(NSString *)lockData
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; success:(TTGetLockConfigSuccessBlock)success
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; failure:(TTFailedBlock)failure;



type :
TTTamperAlert
TTPrivacyLock


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 中午12:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] Implementation for Privacy lock and tamper alert feature (Issue #10)





 
Hi ,
 
I am currently using TTLock SDK wherein I need to implement privacy lock and tamper alert feature . The implementation include setting and getting the corresponding values of these features from the lock.
 
Please guide .
 Thanks
