### ISSUE TITLE
Cannot get passage mode value 

### ISSUE THREAD

**Issue by ghost** [ttlock/iOS_SDK_Demo#11]
I am using TTLock.getPassageModes(withLockData: lockData) to get passage mode value for my lock , it works in majority cases but in some locks there is error obtaining the same . Usually resulting in the error with code 99 , below is a snippet of error received .

`invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
"TTLock Error : TTError(rawValue: 99)"
"TTLock Error Msg : Optional(\"Bluetooth has disconnected, please try again\")"`

Please advice.

**Comment by JuannyiOS** [comment]
Hi ,
If the probability of error is low, i think it is normal.
If only some locks fail frequently, it may be related to the lock hardware. Please send the account number and lock name to us for checking.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上8:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] Cannot get passage mode value  (Issue #11)





 
I am using TTLock.getPassageModes(withLockData: lockData) to get passage mode value for my lock , it works in majority cases but in some locks there is error obtaining the same . Usually resulting in the error with code 99 , below is a snippet of error received .
 
"TTLock Error : TTError(rawValue: 99)" "TTLock Error Msg : Optional(\"Bluetooth has disconnected, please try again\")"
 
Please advice.
