### ISSUE TITLE
How to use this sdk delegate in swift?

### ISSUE THREAD

**Issue by kundan1293** [ttlock/iOS_SDK_Demo#13]
I am having some difficulty implementing the delegate methods in Swift.
- How to declare the TTLock delegate protocol in Swift?
- How to properly implement the delegate methods in Swift?
- Any examples or code snippets would be greatly appreciated.

**Comment by JuannyiOS** [comment]
1.&nbsp;delegate protocol&nbsp;is not used in the TTLock
2. just call&nbsp;methods&nbsp;directly


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 中午1:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] How to use this sdk delegate in swift? (Issue #13)





 
I am having some difficulty implementing the delegate methods in Swift.
  
How to declare the TTLock delegate protocol in Swift?
 
How to properly implement the delegate methods in Swift?
 
Any examples or code snippets would be greatly appreciated.

**Comment by JuannyiOS** [comment]
1.delegate protocol is not used in the TTLock
2. just call methods directly

**Comment by kundan1293** [comment]
Thank you for clarification.

**Comment by kundan1293** [comment]
Any examples or code snippets would be greatly appreciated.
