### ISSUE TITLE
In iOS , TTLock getOperationLog returns operation record with uid 0

### ISSUE THREAD

**Issue by ghost** [ttlock/iOS_SDK_Demo#14]
I am currently trying to fetch operation log using your SDK , but when I uploaded to the log to server , the username came as null. On further inspection , I found that when operation record is fetched before uploading the corresponding uid is 0 . How can I solve this problem.

**Comment by JuannyiOS** [comment]
"uid" is included in “lockData”.
The lockData returned from SDK does not have uid,  you need to get lockData from the server.

**Comment by ashinasok** [comment]
But I could unlock the door with the same lockData , but only in log fetch issue came.

**Comment by JuannyiOS** [comment]
Lockdata with or without uid can be successfully used to unlock.
You need to get lockData from the server interface:
https://euopen.sciener.com/document/doc?urlName=cloud%2Flock%2Flist.html

**Comment by JuannyiOS** [comment]
NO.
Maybe this server interface can help you :
https://euopen.sciener.com/document/doc?urlName=cloud%2Fekey%2Fget.html

**Comment by ashinasok** [comment]
Ok Thanks . Also , is this api invalid now : https://euopen.sciener.com/document/doc?urlName=cloud%2Flock%2FupdateLockData.html . Should we still call it after modifying the feature value of the lock. If this is not invalid couldn't we just use this for the above case?

**Comment by JuannyiOS** [comment]
Invalid !
Yes , you need to call it after modifying the feature value of the lock.
You can use this for the above case. Sorry, I didn't understand you before.

**Comment by JuannyiOS** [comment]
Valid !
You need to call it after modifying the feature value of the lock.
We can use this for the above case. sorry, I didn't understand you before.

**Comment by ashinasok** [comment]
username in unlock records api came as null. how can we solve it?

**Comment by JuannyiOS** [comment]
getOperationLog returns operation record has uid ?
if has uid ,please send the uid to me, we check it
