### ISSUE TITLE
Not seeing TTDoorSensor class

### ISSUE THREAD

**Issue by LiborZa** [ttlock/iOS_SDK_Demo#15]
Hello,

I'm using the TTLock.framework in my Swift project in Xcode. In Headers, there is "@interface TTDoorSensor : NSObject", but when I try to use the 'TTDoorSensor' class in Swift, I get the error message "Cannot find 'TTDoorSensor' in scope". Could you provide some guidance on what I can do to resolve this issue?

Other classes like TTLock, TTWirelessKeypad and TTWirelessKeyFob I have no problem with and I am using it in code. I tried demo app here with ObjectiveC and it seems it has same issue. There must be something missing in header for framework.

Thanks for help,
Libor

**Comment by LiborZa** [comment]
Can anyone help me please?

**Comment by JuannyiOS** [comment]
Sorry, I did not see your message before. There is an issue with the import. SDK has now been updated with version number 3.2.9. Please update and try it.

**Comment by LiborZa** [comment]
Seems like its working now. Thanks
