### ISSUE TITLE
xcode 15 ld: 32 duplicate symbols

### ISSUE THREAD

**Issue by lkuraer** [ttlock/iOS_SDK_Demo#17]
can't launch project with ttlock on xcode 15. pls. fix

duplicate symbol '_OBJC_CLASS_$_HFSmartLinkDeviceInfo' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][15](HFSmartLinkDeviceInfo.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][11](HFSmartLinkDeviceInfo.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.withV3x' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.recvmsg' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.cont' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_METACLASS_$_Udpproxy' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink._isConfigOneDevice' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLinkDeviceInfo._ip' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][15](HFSmartLinkDeviceInfo.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][11](HFSmartLinkDeviceInfo.o)
duplicate symbol '_OBJC_METACLASS_$_HFSmartLinkDeviceInfo' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][15](HFSmartLinkDeviceInfo.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][11](HFSmartLinkDeviceInfo.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.localAdd' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.udp' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.pswd' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.stopBlock' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.remoteAdd' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.endBlock' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.sockfd' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.num' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.deviceDic' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.processBlock' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink._waitTimers' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.isconnnecting' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.sockMCast' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.sendmsg' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLinkDeviceInfo._mac' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][15](HFSmartLinkDeviceInfo.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][11](HFSmartLinkDeviceInfo.o)
duplicate symbol '_OBJC_CLASS_$_HFSmartLink' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.failBlock' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.cont_len' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.successBlock' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_METACLASS_$_HFSmartLink' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_IVAR_$_Udpproxy.findAdd' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.userStoping' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
duplicate symbol '_OBJC_CLASS_$_Udpproxy' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][14](Udpproxy.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][10](Udpproxy.o)
duplicate symbol '_OBJC_IVAR_$_HFSmartLink.sendTime' in:
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][12](HFSmartLink.o)
    -/Pods/TTLockGateway/TTLockFrameworks/TTLockGateway.framework/TTLockGateway[arm64][8](HFSmartLink.o)
ld: 32 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LiborZa** [comment]
For me helped: Add "-ld64" under Build Setting -> Other Linker Flags  but it seems to be workaround and must be fixed.

[More info](https://developer.apple.com/forums/thread/736590)

**Comment by JuannyiOS** [comment]
Thank you for your feedback. It will be updated today.
