### ISSUE TITLE
How to downgrade lock firmware version?

### ISSUE THREAD

**Issue by pathanparvezkhan** [ttlock/iOS_SDK_Demo#19]
We are implementing upgrade lock firmware version functionality. We are using below SDK method from TTLockDFU library.

TTLockDFU.shareInstance().start(withClientId: clientId, accessToken: accessToken, lockId: lockId, lockData: lockData) { upgradeOperation, process in
            print(upgradeOperation)
        } fail: { upgradeOperation, upgradeErrorCode in
            print(upgradeOperation)
            print(upgradeErrorCode)
        }

We have all the locks available with latest firmware version. We want to downgrade the firmware version of lock to test this feature.

**Comment by JuannyiOS** [comment]
ok, please provide the test account and  test lock number(lock name).

**Comment by pathanparvezkhan** [comment]
> ok, please provide the test account and test lock number(lock name).

Test Account:
jackey.kabra@geokeyaccess.com
Admin@123

Lock number(lock name):
M515_a8757c

**Comment by JuannyiOS** [comment]
Done !

**Comment by pathanparvezkhan** [comment]
> Done !

Also need to downgrade version for below lock for same account.

Lock number(lock name):
Jackey TTLock1

**Comment by JuannyiOS** [comment]
This lock currently does not have an upgrade package. Do you have any other locks ？

**Comment by pathanparvezkhan** [comment]
> This lock currently does not have an upgrade package. Do you have any other locks ？

Please find the below 2 locks.

Lock number(lock name):
MyTestLock2023/11/23 17:54:09
MyTestLock2023/11/23 17:54:33

Can we downgrade here at our end? If yes, please give us steps.

**Comment by JuannyiOS** [comment]
Done !

**Comment by pathanparvezkhan** [comment]
> Done !

Thank You.

**Comment by JackeyPSSPL** [comment]
@JuannyiOS Can we downgrade here at our end? If yes, please give us the steps.

**Comment by JuannyiOS** [comment]
sorry ,you can not downgrade locks at your end.

**Comment by JackeyPSSPL** [comment]
@JuannyiOS Can you again downgrade the below locks?

Please find the below 2 locks.

Lock number(lock name):
1. MyTestLock2023/11/23 17:54:33
2. Test

**Comment by JuannyiOS** [comment]
The unlimited upgrade that has already been configured.

**Comment by JuannyiOS** [comment]
Add the lock again then upgrade again

**Comment by JackeyPSSPL** [comment]
@JuannyiOS Added devices please find below the downgrade it

1. MyTestLock2023/11/28 23:02:42
2. MyTestLock2023/11/28 23:03:15
3. MyTestLock2023/11/28 23:05:13

Thank you

**Comment by JuannyiOS** [comment]
Have these three locks been configured before? If it has been configured, you can upgrade it again by adding it again.
If these are three new locks，please contact with this email：ttlock-developers-email-list@googlegroups.com.
