### ISSUE TITLE
TTGateway initialization fails

### ISSUE THREAD

**Issue by S3basuchian** [ttlock/iOS_SDK_Demo#2]
Hello,
When I call `TTGateway initializeGatewayWithInfoDic` after I have connected the Gateway nothing happens for like 2 minutes after which the block is called with `TTGatewayStatus = TTGatewayDisconnect`. There are no other error messages. Why is this happening?

**Comment by S3basuchian** [comment]
If anyone else is wondering:
The iOS SDK needs the plaintext user password (in contrast to Android, which needs the md5 password). An error message that the password is wrong would be nice regardless

**Comment by ttlock** [comment]
hi,sorry for the trouble! the plaintext user password and MD5 password are all OK in the lastest iOS sdk.

**Comment by S3basuchian** [comment]
Thanks for the heads up. I'm using the latest version from Cocoapods, which I guess is not the very latest version then?

**Comment by ttlock** [comment]
yes,we can't get the verification code of cocoapods,so the latest versions haven't submitted to cocoapods.You can download the latest version through this website.

**Comment by mehulparmar4ever** [comment]
**### Can someone please guide me? #Urgent #Please**

I am also facing same error.

Here is the TTGateway.initializeGateway(withInfoDic: infoDic)

`let infoDic = [
                        "SSID": self.txtWifiName.text!,
                        "wifiPwd": self.txtWifiPassword.text!,
                        "uid": uid ,
                        "userPwd": password,
                        "gatewayName": self.txtWifiName.text!
                    ]`
![Screenshot 2020-10-08 at 11 17 23 AM](https://user-images.githubusercontent.com/7687920/95419763-e09b2200-0957-11eb-9275-3f9fcd474770.png)

![11](https://user-images.githubusercontent.com/7687920/95419652-ae89c000-0957-11eb-9837-70f2c6d6e31f.jpeg)
![22](https://user-images.githubusercontent.com/7687920/95419660-b21d4700-0957-11eb-80c0-712cb5221f2e.jpeg)
