### ISSUE TITLE
Swift Package Manager support for TTlock SDK.

### ISSUE THREAD

**Issue by pathanparvezkhan** [ttlock/iOS_SDK_Demo#21]
Do you have a plan to add support for Swift Package Manager to install TTlock SDK?

**Comment by JuannyiOS** [comment]
Thank you for your suggestion. Let's take a look later, but this priority will be lower.

**Comment by JuannyiOS** [comment]
Let's take a look together.

**Comment by pathanparvezkhan** [comment]
Can we Include TTLock Framework inside a Swift package to distribute code in binary for use in other projects?

**Comment by JuannyiOS** [comment]
Swift Package Manager currently has no plan.
Updated xcframework  , version 3.3.0

**Comment by pathanparvezkhan** [comment]
> Swift Package Manager currently has no plan. Updated xcframework , version 3.3.0

What's new in version 3.3.0?

**Comment by pathanparvezkhan** [comment]
> > Swift Package Manager currently has no plan. Updated xcframework , version 3.3.0
> 
> What's new in version 3.3.0?

**Comment by JuannyiOS** [comment]
support xcframework




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 下午3:56
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ttlock/iOS_SDK_Demo] Swift Package Manager support for TTlock SDK. (Issue #21)





  
Swift Package Manager currently has no plan. Updated xcframework , version 3.3.0
  
What's new in version 3.3.0?
