### ISSUE TITLE
What's new in updated Xcframework version 3.3.0?

### ISSUE THREAD

**Issue by pathanparvezkhan** [ttlock/iOS_SDK_Demo#22]

**Comment by JuannyiOS** [comment]
It just supports xcframework.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 下午4:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] What's new in updated Xcframework version 3.3.0? (Issue #22)
