### ISSUE TITLE
autoUnlock Issue: Config the passage mode of a lock

### ISSUE THREAD

**Issue by pathanparvezkhan** [ttlock/iOS_SDK_Demo#23]
We are using below API for the passage mode 'autoUnlock'.

https://euapi.ttlock.com/v3/lock/configPassageMode

We are passing 1 in autoUnlock parameter but It is not unlocking lock at given scheduled time.

**Comment by ttlock** [comment]
you need to call iOS sdk method "configPassageMode" first, then call "https://euapi.ttlock.com/v3/lock/configPassageMode".

**Comment by pathanparvezkhan** [comment]
> you need to call iOS sdk method "configPassageMode" first, then call "https://euapi.ttlock.com/v3/lock/configPassageMode".

Tried this but not working. Is it possible to achieve directly through API from our backend? I don't want iOS sdk method call dependency.

**Comment by ttlock** [comment]
There is a parameter "type" in this interface "https://euapi.ttlock.com/v3/lock/configPassageMode" ,if this lock is a WiFi lock or has a gateway.
If it's not an SDK bug issue, you can contact email "ttlock-developers-email-list@googlegroups.com".
