### ISSUE TITLE
Upload data functionality in TTlock App.

### ISSUE THREAD

**Issue by pathanparvezkhan** [ttlock/iOS_SDK_Demo#24]
![Skype_Picture_2024_01_09T13_37_02_108Z](https://github.com/ttlock/iOS_SDK_Demo/assets/1358698/8b9e63a6-0389-4df6-8cee-12d40e133e26)

Upload data functionality: We want to achieve the same functionality as in TTlock App. I have attached here screenshot for the same. 

Could you please provide the details for the relevent SDK method / API to achieve the same functionality in our app?

**Comment by ttlock** [comment]
If it's not an SDK bug issue, you can contact email :ttlock-developers-email-list@googlegroups.com.
There will be technical support to answer your questions

**Comment by ttlock** [comment]
1 upload lock record
api: https://euopen.sciener.com/document/doc?urlName=cloud%2FlockRecord%2Fupload.html
sdk: + (void)getOperationLogWithType:(TTOperateLogType)type
                       lockData:(NSString *)lockData
                        success:(TTGetLockOperateRecordSucceedBlock)success
                        failure:(TTFailedBlock)failure;

2 upload passcodes
api: https://euopen.sciener.com/document/doc?urlName=cloud%2Fpasscode%2FuploadEn.html
sdk:+ (void)getPasscodeVerificationParamsWithLockData:(NSString *)lockData
                                          success:(TTGetPasscodeVerificationParamsSucceedBlock)success
                                          failure:(TTFailedBlock)failure;
