### ISSUE TITLE
"Daylight saving setting": What does this feature do? How to implement it?

### ISSUE THREAD

**Issue by pathanparvezkhan** [ttlock/iOS_SDK_Demo#25]
![Screenshot 2024-01-16 at 2 26 41 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/1358698/b223f579-f571-41c5-ad66-8245489260e5)

**Comment by pathanparvezkhan** [comment]
Please provide the details for implementation SDK method or API.

**Comment by ttlock** [comment]
It's quite troublesome to implement this using the existing interface. We will discuss it tomorrow and get back to you as soon as possible

**Comment by ttlock** [comment]
After setting the lock time by SDK, then call the API to update the time zone, then update the lockdata you are using.

SDK:+ (void)setLockTimeWithTimestamp:(long long)timestamp
                        lockData:(NSString *)lockData
                         success:(TTSucceedBlock)success
                         failure:(TTFailedBlock)failure;
note: timestamp =  currentTimeStamp + (currentTimezoneRawOffSet - key.timezoneRawOffset);
currentTimeStamp : The timestamp of the current time (in millisecond)
currentTimezoneRawOffSet：The offset between your time zone and UTC, in millisecond .For example UTC+8 is 28800000.
key.timezoneRawOffset：the lock detail returned by the server interface(https://cnopen.sciener.com/document/doc?urlName=cloud%2Flock%2Fdetail.html)
          
                 
API :https://euopen.sciener.com/document/doc?urlName=cloud%2Flock%2FchangeTimezoneRawOffsetEn.html
