### ISSUE TITLE
Unlocking Lock Using iPhone NFC without NFC Tags/Cards

### ISSUE THREAD

**Issue by pinalpsspl** [ttlock/iOS_SDK_Demo#27]
We're reaching out to request guidance and explore potential solutions regarding the integration of iPhone NFC capabilities for unlocking locks, akin to the convenience offered by Apple Pay, without necessitating the use of NFC tags or cards.

Possible solutions: 
- HomeKey:- https://support.apple.com/en-in/guide/iphone/iph0dc255875/ios
- PassKit:- https://developer.apple.com/wallet/get-started/

**Comment by pinalpsspl** [comment]
@ttlock any update on the above query? 

Adding to the above query:- 

1. Does TTLock NFC reader support this protocol - https://support.apple.com/en-in/guide/security/secbd55491ad/web ?
2. Can you tell us what information we will need to store in the NFC payload of the pass created by Passkit and unlock the lock. 
For example i create pass using this payload will it work ?, here 850714397 is card number generated by ttlock SDK's addICCardWithCyclicConfig function.

{
    "passTypeIdentifier": "pass.com.ttlock",
    "serialNumber": "850714397",
    "teamId": "XXXXXXXXXX",
    "organizationName" : "TTLock",
    "description": "TTLock",
    "foregroundColor": "rgb(255, 255, 255)",
    "backgroundColor": "rgb(0, 0, 0)",
    "nfc": {
        "message": "850714397"
    }
}

**Comment by JuannyiOS** [comment]
sorry, apple does not open NFC functionality to all,  we can not add NFC card by apple app.
