### ISSUE TITLE
Get all logs from TTLock SDK. 

### ISSUE THREAD

**Issue by davemccollough-geokey** [ttlock/iOS_SDK_Demo#29]
```
TTLock.getOperationLog(with: .all, lockData: lockdata) { value in
                        
                    } failure: { errorCode, errorMsg in
                        
                    }
```

When I call the above method with `.all`, it returns too many records. I just want to confirm, does the method have a limit on the number of records it returns for a specified duration, such as 6 months or 1 year?

**Comment by JuannyiOS** [comment]
The records stored in the lock are not related to the duration of time. Locks have a maximum storage quantity, exceeding which will overwrite previous records. The maximum quantity may be 1000 or 1500 or other, depending on the lock.
