### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by LiborZa** [ttlock/iOS_SDK_Demo#3]
Hi,
it's great library and it's working fine. I am thinking about creating watchOS app too and I would like to be almost independet app. Are you planning to get library building and working in watchOS? At least for locking or unlocking.
Thanks for info

**Comment by ahmedalttai** [comment]
> Hi,
> it's great library and it's working fine. I am thinking about creating watchOS app too and I would like to be almost independet app. Are you planning to get library building and working in watchOS? At least for locking or unlocking.
> Thanks for info

Hi,
Did you manage to get the library working with watchOs for linked watch app with IOS app?

**Comment by ttlock** [comment]
Hi,can you provide your email? I send the sdk for watchOS to you.

**Comment by ahmedalttai** [comment]
> Hi,can you provide your email? I send the sdk for watchOS to you.

admin@ahma.me

thank you

**Comment by JuannyiOS** [comment]
1.Drag the “TTLock.framework” into the project.&nbsp;


2.Find Target-&gt;Build Phases -&gt; Link Binary With Libraries ,add CoreBluetooth.framework.


3.Find Target-&gt;Build Settings -&gt; Linking -&gt; Other Linker Flags ,add “-ObjC”（If it already exists, there is no need to add it.）


4.Import header file
#import <TTLock/TTLock.h&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 晚上8:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ttlock/iOS_SDK_Demo] watchOS support (#3)





  
Hi,can you provide your email? I send the sdk for watchOS to you.
  
***@***.***
 
thanks
 
Btw why it's not public?

**Comment by JuannyiOS** [comment]
Find Target-&gt;Build Settings -&gt; Linking -&gt; Other Linker Flags ,add “-ObjC”（If it already exists, there is no need to add it.）







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 晚上8:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ttlock/iOS_SDK_Demo] watchOS support (#3)





  
Hi,can you provide your email? I send the sdk for watchOS to you.
  
***@***.***
 
thanks
 
Btw why it's not public?
