### ISSUE TITLE
Request for Privacy Changes Updates in SDK and Required Signed XCFramework.

### ISSUE THREAD

**Issue by parvezkhanpsspl** [ttlock/iOS_SDK_Demo#30]
1. We are using the TTLock third-party SDK in our iOS project. Could you please confirm whether you are planning to adopt the privacy changes mentioned in the article "Privacy changes for app developers"? This is important because failure to comply could result in Apple rejecting our app. Please find the below reference links.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

https://www.adjust.com/blog/privacy-changes-for-app-developers-ios-17/

2. Additionally, we require a signed XCFramework for the TTLock.  As we are using it as Swift package.

https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks

**Comment by JuannyiOS** [comment]
Ok, we have received it and will reply in the next two days.

**Comment by parvezkhanpsspl** [comment]
> Ok, we have received it and will reply in the next two days.

Ok, Thank you for quick response.

**Comment by JuannyiOS** [comment]
The listed SDKs will affect app release.
https://developer.apple.com/cn/support/third-party-SDK-requirements/

This SDK does not require any privacy , you can use it with confidence.

**Comment by parvezkhanpsspl** [comment]
> The listed SDKs will affect app release. https://developer.apple.com/cn/support/third-party-SDK-requirements/
> 
> This SDK does not require any privacy , you can use it with confidence.

Thank you for the clarification.

**Comment by parvezkhanpsspl** [comment]
We also required signed Xcframework for TTlock. Any update on the same?

https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks

**Comment by JuannyiOS** [comment]
The listed SDKs will affect app release. 
https://developer.apple.com/cn/support/third-party-SDK-requirements/

This SDK does not require signed.

**Comment by parvezkhanpsspl** [comment]
We require a signed XCFramework for TTlock to be used within a Swift package, allowing it to be utilized in other projects.

We have tried with current unsigned XCFramework but getting an error. Please find the below attached error screenshot.

![Screenshot 2024-03-18 at 12 21 47 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/b61f08f4-785c-48f4-a4e9-057252a630a7)

**Comment by JuannyiOS** [comment]
[TTLock.xcframework.zip](https://github.com/ttlock/iOS_SDK_Demo/files/14691968/TTLock.xcframework.zip)

please try this one. if ok, we will update it.

**Comment by parvezkhanpsspl** [comment]
> [TTLock.xcframework.zip](https://github.com/ttlock/iOS_SDK_Demo/files/14691968/TTLock.xcframework.zip)
> 
> please try this one. if ok, we will update it.

Thank you for sharing signed Xcframework quickly. We tried to add into watchOS target but we face below error.

While building for watchOS, no library for this platform was found in '/Frameworks/TTLock.xcframework'.

So kindly request to send us updated signed Xcframework with watchOS support.

**Comment by davemccollough-geokey** [comment]
> [TTLockWatchOS.xcframework.zip](https://github.com/ttlock/iOS_SDK_Demo/files/14692984/TTLockWatchOS.xcframework.zip)
> 
> please try this one.

Thanks for sharing the watch Xcframework! 
 
We noticed an update for TTLock framework. Could you please add the watch Xcframework to the repo? 
This ensures any changes in TTLock framework also apply to the watch OS Xcframework. 
 
Appreciate your help!

**Comment by JuannyiOS** [comment]
Updated watch OS Xcframework

**Comment by parvezkhanpsspl** [comment]
> Updated watch OS Xcframework

Where is it?

**Comment by JuannyiOS** [comment]
https://github.com/ttlock/watchOS_SDK
