### ISSUE TITLE
Facing issue in adding G3 gateway after updating to New firmware version.

### ISSUE THREAD

**Issue by parvezkhanpsspl** [ttlock/iOS_SDK_Demo#31]
TTLock SDK pod version: 3.3.10

G2 Gateway: Working fine even after updating it to new version.

G3 Gateway: It was working fine with previous version 6.0.0.220224, As there was an update available, we have updated it to new version 6.0.0.231007. Now getting timeout error consistently while adding gateway.

MAC address: 11:77:6D:0E:63:A5
Model: G3P

Please find my below code snippets to initialize gateway:

```
var infoDic: [AnyHashable: Any]
        infoDic = [
            "SSID": SSID,
            "wifiPwd": wifiPwd,
            "userPwd": ttlockAccountPassword,
            "gatewayName": networkName,
            "uid": ttlockAccountUid
        ]
        
        TTGateway.initializeGateway(withInfoDic: infoDic) { _ , gatewayStatus in
            if gatewayStatus == .success {
               print("success")
               TTGateway.disconnectGateway(withGatewayMac: self.gatewayMac, block: nil)
            } else {
                print("error")
            }
        }
```

**Comment by parvezkhanpsspl** [comment]
> TTLock SDK pod version: 3.3.10
> 
> G2 Gateway: Working fine even after updating it to new version.
> 
> G3 Gateway: It was working fine with previous version 6.0.0.220224, As there was an update available, we have updated it to new version 6.0.0.231007. Now getting timeout error consistently while adding gateway.
> 
> MAC address: 11:77:6D:0E:63:A5 Model: G3P
> 
> Please find my below code snippets to initialize gateway:
> 
> ```
> var infoDic: [AnyHashable: Any]
>         infoDic = [
>             "SSID": SSID,
>             "wifiPwd": wifiPwd,
>             "userPwd": ttlockAccountPassword,
>             "gatewayName": networkName,
>             "uid": ttlockAccountUid
>         ]
>         
>         TTGateway.initializeGateway(withInfoDic: infoDic) { _ , gatewayStatus in
>             if gatewayStatus == .success {
>                print("success")
>                TTGateway.disconnectGateway(withGatewayMac: self.gatewayMac, block: nil)
>             } else {
>                 print("error")
>             }
>         }
> ```

Any update on above issue?

**Comment by JuannyiOS** [comment]
New version 6.0.0.231007 is ok. We have  extensive testing before releasing it to the public.
We cannot determine the reason for this.
Please Re Connect the Power before adding gateway.
![Uploading IMG_4158.PNG…]()

**Comment by JuannyiOS** [comment]
![IMG_4158](https://github.com/ttlock/iOS_SDK_Demo/assets/15101581/75952d80-5430-4b9a-a8da-e670fff8a9cb)

**Comment by pathanparvezkhan** [comment]
> ![IMG_4158](https://private-user-images.githubusercontent.com/15101581/328495212-75952d80-5430-4b9a-a8da-e670fff8a9cb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODI3ODcsIm5iZiI6MTcxNTA4MjQ4NywicGF0aCI6Ii8xNTEwMTU4MS8zMjg0OTUyMTItNzU5NTJkODAtNTQzMC00YjlhLWE4ZGEtZTY3MGZmZjhhOWNiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDExNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOWM5YTg5OTA0MjkxY2NhNzM2NjFiNmE4MTcwODBjZmEyYzE0NmYwMTA4N2ZmYWFlYWJmZmU2OTZlZGFlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CLxoC6_xNg8iN7Tl55pepazmwRtsBczGZOy5akuAXDs)

We have tried reconnecting power before adding gateway. But issue is still persist with the G3 gateway version 6.0.0.231007.

We have captured code debugging video for the same. Please check and let us know if any change is required.

https://github.com/ttlock/iOS_SDK_Demo/assets/1358698/5daece2b-5946-4c73-be6d-b23e7bb3bf9a

**Comment by pathanparvezkhan** [comment]
> ![IMG_4158](https://private-user-images.githubusercontent.com/15101581/328495212-75952d80-5430-4b9a-a8da-e670fff8a9cb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODI3ODcsIm5iZiI6MTcxNTA4MjQ4NywicGF0aCI6Ii8xNTEwMTU4MS8zMjg0OTUyMTItNzU5NTJkODAtNTQzMC00YjlhLWE4ZGEtZTY3MGZmZjhhOWNiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDExNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOWM5YTg5OTA0MjkxY2NhNzM2NjFiNmE4MTcwODBjZmEyYzE0NmYwMTA4N2ZmYWFlYWJmZmU2OTZlZGFlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CLxoC6_xNg8iN7Tl55pepazmwRtsBczGZOy5akuAXDs)

We have tried reconnecting power before adding gateway. But issue is still persist with the G3 gateway version 6.0.0.231007.

We have captured code debugging screen shots for the same. Please check and let us know if any change is required.

<img width="944" alt="Screenshot 2024-05-07 at 5 39 45 PM" src="https://github.com/ttlock/iOS_SDK_Demo/assets/1358698/c3842a1f-dd5f-45a3-a975-31b4a911afcb">

<img width="1300" alt="Screenshot 2024-05-07 at 5 40 00 PM" src="https://github.com/ttlock/iOS_SDK_Demo/assets/1358698/6194a478-8450-4930-8914-19adc525d4c2">

**Comment by parvezkhanpsspl** [comment]
> > ![IMG_4158](https://private-user-images.githubusercontent.com/15101581/328495212-75952d80-5430-4b9a-a8da-e670fff8a9cb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODI3ODcsIm5iZiI6MTcxNTA4MjQ4NywicGF0aCI6Ii8xNTEwMTU4MS8zMjg0OTUyMTItNzU5NTJkODAtNTQzMC00YjlhLWE4ZGEtZTY3MGZmZjhhOWNiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDExNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOWM5YTg5OTA0MjkxY2NhNzM2NjFiNmE4MTcwODBjZmEyYzE0NmYwMTA4N2ZmYWFlYWJmZmU2OTZlZGFlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CLxoC6_xNg8iN7Tl55pepazmwRtsBczGZOy5akuAXDs)
> 
> We have tried reconnecting power before adding gateway. But issue is still persist with the G3 gateway version 6.0.0.231007.
> 
> We have captured code debugging screen shots for the same. Please check and let us know if any change is required.
> 
> <img alt="Screenshot 2024-05-07 at 5 39 45 PM" width="944" src="https://private-user-images.githubusercontent.com/1358698/328516348-c3842a1f-dd5f-45a3-a975-31b4a911afcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTU4NDQsIm5iZiI6MTcxNTc1NTU0NCwicGF0aCI6Ii8xMzU4Njk4LzMyODUxNjM0OC1jMzg0MmExZi1kZDVmLTQ1YTMtYTk3NS0zMWI0YTkxMWFmY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDY0NTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZhYzIxOTAxNjBlYmUwYzNmOTVkNjAwZTRhY2Q4MDNmN2VkNDdiZDE1ZTA4NjFjYTE3YzRkOWM5NjY1NjgzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4LuuZF9shLRPqnUjPAtVXJvhooXHBU105Yj1yh_GH4k"> <img alt="Screenshot 2024-05-07 at 5 40 00 PM" width="1300" src="https://private-user-images.githubusercontent.com/1358698/328516428-6194a478-8450-4930-8914-19adc525d4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTU4NDQsIm5iZiI6MTcxNTc1NTU0NCwicGF0aCI6Ii8xMzU4Njk4LzMyODUxNjQyOC02MTk0YTQ3OC04NDUwLTQ5MzAtODkxNC0xOWFkYzUyNWQ0YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDY0NTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI0Yzg2ZTJhZjVjMjRlODMzN2U0NWQ1NWJmMGY5ZGFiZjNhOTFkOTEzYzkwYzdjNzM0Y2RkZTUzNDg4NmJkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qXqW77emAyx2XRQ6u940Ur-Mrlpc_evW7WeWKau0ARc">

Any update on above issue?

**Comment by ttlock** [comment]
Can you change a gateway? Maybe this gateway is broken.

**Comment by davemccollough-geokey** [comment]
> Can you change a gateway? Maybe this gateway is broken.

We have two G3 gateways and encountered the same issue with both. We resolved the issue on one of the gateways by adding it using the TTlock iOS official app downloaded from the App Store. We have not faced any issues with it since then. Below are the details of the device that is no longer experiencing any issues:

MAC address: 32:7F:33:8C:A0:16
Model: G3P

However, we are still facing the issue with the other gateway. We have not tried adding it using the TTlock official app yet. It might get fixed if we do so, but it should not be necessary to use the app to resolve this issue.

Below are the details of the device still facing the issue:

MAC address: 11:77:6D:0E:63:A5
Model: G3P

**Comment by parvezkhanpsspl** [comment]
> Can you change a gateway? Maybe this gateway is broken.

We have two G3 gateways and encountered the same issue with both. We resolved the issue on one of the gateways by adding it using the TTlock iOS official app downloaded from the App Store. We have not faced any issues with it since then. Below are the details of the device that is no longer experiencing any issues:

MAC address: 32:7F:33:8C:A0:16
Model: G3P

However, we are still facing the issue with the other gateway. We have not tried adding it using the TTlock official app yet. It might get fixed if we do so, but it should not be necessary to use the app to resolve this issue.

Below are the details of the device still facing the issue:

MAC address: 11:77:6D:0E:63:A5
Model: G3P

**Comment by ttlock** [comment]
Add a parameter "gatewayVersion", 
ginfoDic[@"gatewayVersion"]= @2;  //@2 means G2,@3 means G3,@4 means G4
<img width="988" alt="Add a parameter  gatewayVersion" src="https://github.com/ttlock/iOS_SDK_Demo/assets/26622367/8ae26b6e-1124-4e5e-8d4f-1efa1839973a">

**Comment by parvezkhanpsspl** [comment]
> Add a parameter "gatewayVersion", ginfoDic[@"gatewayVersion"]= @2; //@2 means G2,@3 means G3,@4 means G4 <img alt="Add a parameter gatewayVersion" width="988" src="https://private-user-images.githubusercontent.com/26622367/331434628-8ae26b6e-1124-4e5e-8d4f-1efa1839973a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjcwOTMsIm5iZiI6MTcxNTkyNjc5MywicGF0aCI6Ii8yNjYyMjM2Ny8zMzE0MzQ2MjgtOGFlMjZiNmUtMTEyNC00ZTVlLThkNGYtMWVmYTE4Mzk5NzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA2MTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MWJlOTM3NzQzN2ZjYjNiZTQ1OWI1MDllOWY4MGJmN2U2ZWU5MGY2YzI2NWM5NTk4Y2NhZGMxZTUxNDUyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aC_9HW0ojqLlVQrlUCq8zw_Tz1bzKO5rjHtyx1OPfz0">

We added the "gatewayVersion" parameter but the issue remains. We also tried reconnecting the power before adding the gateway. Every time we attempt to add it, we get a gateway timeout error. Please find the updated code screenshots attached for your reference.

![Screenshot 2024-05-17 at 11 48 51 AM](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/85d84387-c043-4825-85d3-2fed5efd7993)

![Screenshot 2024-05-17 at 11 48 24 AM](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/a9930e46-76f8-4ce8-8d29-f788a6da06df)

**Comment by parvezkhanpsspl** [comment]
> Sorry for the inconvenience caused to you. Thank you for your feedback. We have identified the cause, please update SDK v3.3.11.

Thank you for your prompt response and assistance.

I have updated SDK to v3.3.11 as you recommended, and I am pleased to confirm that the issue has been resolved. Both gateways are now functioning correctly without any errors. I appreciate your swift support in resolving this matter.

Thank you once again for your help.
