### ISSUE TITLE
Need to downgrade gateway firmware version.

### ISSUE THREAD

**Issue by parvezkhanpsspl** [ttlock/iOS_SDK_Demo#32]
We are implementing upgrade gateway firmware version functionality. We are using below SDK method from TTLockDFU library.

```
TTGatewayDFU.shareInstance().start(with: .byNet, clientId: "clientId", accessToken: "accessToken", gatewayId: "gatewayId", gatewayMac: "gatewayMac") { status, progress in
            if(status == .success) {
                print("Gateway firmware update success.")
            }
        } fail: { status, error in
            print(error)
        }
```

We have all the gateways available with latest firmware version. We want to downgrade the firmware version of lock to test this feature.

Please find the below test account and gateway details:

Test Account:
jackey.kabra@geokeyaccess.com
Admin@123 

Gateway Details:
Name: G2 -1
Gateway Id: 530564
Gateway Mac: "D4:B4:75:0B:01:8D"

Name: G2-2
Gateway Id: 531598
Gateway Mac: "D5:41:D5:DD:6F:D5"

Name: G3-4 
Gateway Id: 519802
Gateway Mac: "16:A0:8C:33:7F:33"

Please downgrade firmware versions for all above 3 gateways.

**Comment by JuannyiOS** [comment]
Unlimited upgrades have been configured. Please add the gateway again before each upgrade.

**Comment by pathanparvezkhan** [comment]
> Unlimited upgrades have been configured. Please add the gateway again before each upgrade.

Thank you for your support.

**Comment by pathanparvezkhan** [comment]
> Unlimited upgrades have been configured. Please add the gateway again before each upgrade.

Unable downgrade again after adding the same gateway to that test account. Can you provide us steps to re-downgrade?

**Comment by JuannyiOS** [comment]
we cannot downgrade the gateway.  Unlimited upgrades are just for you to test upgrades.

**Comment by davemccollough-geokey** [comment]
> Unlimited upgrades have been configured. Please add the gateway again before each upgrade.

As you have Unlimited upgrades, I have tried upgrading G2 gateway from your provided iOS demo app to verify if it is working or not. But getting an error "UpgradeErrorNONeedUpgrade". I have attached below code debugging screen shots. Please find below screenshots.

![Screenshot 2024-05-08 at 11 47 08 AM](https://github.com/ttlock/iOS_SDK_Demo/assets/98485073/71f8a6a4-df29-4928-adc0-19cc1775aad7)

![Screenshot 2024-05-08 at 12 00 50 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/98485073/496cd228-00be-4b7d-a6d3-e34af8a91bc7)

**Comment by parvezkhanpsspl** [comment]
> Unlimited upgrades have been configured. Please add the gateway again before each upgrade.

As you have configured unlimited upgrades, I have tried upgrading G2 gateway from your provided iOS demo app to verify if it is working or not. But getting an error "UpgradeErrorNONeedUpgrade". I have attached below code debugging screen shots. Please find below screenshots.

![Screenshot 2024-05-08 at 11 47 08 AM](https://github.com/ttlock/iOS_SDK_Demo/assets/98485073/71f8a6a4-df29-4928-adc0-19cc1775aad7)

![Screenshot 2024-05-08 at 12 00 50 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/98485073/496cd228-00be-4b7d-a6d3-e34af8a91bc7)

**Comment by ttlock** [comment]
You need to use the test account you provided and cannot use any other account.
Test Account:
jackey.kabra@geokeyaccess.com
Admin@123

**Comment by parvezkhanpsspl** [comment]
> You need to use the test account you provided and cannot use any other account. Test Account: [jackey.kabra@geokeyaccess.com](mailto:jackey.kabra@geokeyaccess.com) Admin@123

Yes I have tried with same account but still facing issue while upgrading gateway. I have attached below code debugging screen shots. Please find below screenshots.

GatewayId: 531600
GatewayMAC: F5:D1:D5:BC:4D:05

![Screenshot 2024-05-16 at 6 22 26 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/d0406b9a-36d9-40c2-9ba4-2e9909a1159f)

![Screenshot 2024-05-16 at 6 22 35 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/6b48c361-f0b1-4c7d-90cc-2b59391fd91a)

**Comment by ttlock** [comment]
The gateway you previously provided did not have “F5:D1:D5:BC:4D:05”
please use below
Gateway Details:
Name: G2 -1
Gateway Id: 530564
Gateway Mac: "D4:B4:75:0B:01:8D"

Name: G2-2
Gateway Id: 531598
Gateway Mac: "D5:41:D5:DD:6F:D5"

Name: G3-4
Gateway Id: 519802
Gateway Mac: "16:A0:8C:33:7F:33"
