### ISSUE TITLE
Not able to add G2 Gateway in android

### ISSUE THREAD

**Issue by JackeyPSSPL** [ttlock/iOS_SDK_Demo#34]
@ttlock 

We are currently encountering difficulties in adding a Gateway G2 device using both the TTLock SDK demo and the TTLock application from the Play Store. Despite following the necessary steps and providing all required details, we consistently encounter the error message "FAILED_TO_CONFIGURE_ROUTER."

For our integration efforts, we have utilized the following method from the TTLock SDK:
![image](https://github.com/ttlock/iOS_SDK_Demo/assets/107833037/c3fd95c4-48c2-4af0-a383-792c7f557db0)

Additionally, we attempted to add the Gateway G2 device using the TTLock application, but encountered an issue where the Wi-Fi network name could not be found. We have recorded a video demonstrating this issue, which you can view using the following link:
 
https://github.com/ttlock/iOS_SDK_Demo/assets/107833037/ca082a24-27b6-4886-b3d8-6183e0b285dd

We would appreciate any assistance or guidance you can provide in resolving these issues. Additionally, if there have been any recent updates or changes to the TTLock SDK or application that could affect the process of adding Gateway G2 devices, please let us know.

**Comment by ttlock** [comment]
For issues with the Android SDK, you can send an email to "ttlock-developers-email-list@googlegroups.com".
