### ISSUE TITLE
TTLock: Battery Value Variations between SDK and API

### ISSUE THREAD

**Issue by parvezkhanpsspl** [ttlock/iOS_SDK_Demo#35]
We've noticed some inconsistencies in the battery values retrieved from the TTLock SDK and the TTLock API. This affects both Android and iOS devices across multiple models. Below, We've listed the devices along with the observed battery values.

![Screenshot 2024-05-15 at 12 14 06 PM](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/f8aa39ee-befa-4ea9-ac11-397dbc9d1d4c)
![image](https://github.com/ttlock/iOS_SDK_Demo/assets/162996659/ace449f4-ca93-478f-b2de-b15c3a76b0f1)

iOS SDK Method:
```
TTLock.getElectricQuantity(withLockData: lockData) { value in
    completion(.success(value))
} failure: { _, errorMSG in
    if let errorMSG {
        completion(.failure(TTLockHelperError.custom(errorMSG)))
    } else {
        completion(.failure(TTLockHelperError.somethingWentWrong))
    }
}
```
Android SDK Method:
```
private void getLockBatteryLevel() {
    showConnectLockToast();
    TTLockClient.getDefault().getBatteryLevel(
        mCurrentLock.getLockData(),
        mCurrentLock.getLockMac(),
        new GetBatteryLevelCallback() {
            @Override
            public void onGetBatteryLevelSuccess(int electricQuantity) {
                makeToast("lock battery is " + electricQuantity + "%");
            }
            @Override
            public void onFail(LockError error) {
                makeErrorToast(error);
            }
        });
}

```

Expected Behavior:
The battery values retrieved from both the SDK and the API should be consistent and accurate across all supported devices.

**Comment by ttlock** [comment]
1. TTLock app and TTLock API have done calculations.
 int electricQuantity = electricQuantity / 5  * 5 ;  (such as 18->15, 31->30, 20->20)
2. The reading of electricity level is not as accurate, and a slight fluctuation is normal.
