### ISSUE TITLE
High Failure Rate for Unlock Operations with TTLock SDK

### ISSUE THREAD

**Issue by parvez-geokey** [ttlock/iOS_SDK_Demo#37]
We are currently experiencing significant failures with the unlock operations using your SDK in our iOS and Android applications. Below are the details:

iOS TTLock SDK Version: 3.3.11
Android TTLock SDK Version: 3.2.6

**Issue:**

Over the past two months, we have observed a substantial increase in the failure rate of unlock operations for some of our live users. For certain users, the failure rate exceeds 90%. Initially, we did not encounter such high failure rates.

**Key Points:**

- Occurrence: The issue has been observed for the past three months.
- Failure Rate: Some users are experiencing more than 90% failure in unlock operations.
- Reproducibility: It is reproduced on Android.
- Operations Affected: Unlock operations specifically.
- Functions Used: Lock, unlock, generate pincodes, read battery, etc.
- Error: As we checked logs, in most cases we are getting "Connection timeout" and "lock is busy" errors from the SDK. The issue mostly occurs after we enable and disable mobile WiFi.
- Device: The issue mostly occurs in the TTLock Bluetooth device.

We have not made any significant changes to our integration that could cause this issue. We are concerned that there might be changes or updates in the SDK or its dependencies that could be contributing to this problem.

**Request:**

Could you please investigate this matter and provide insights into any recent changes in the SDK versions mentioned that might be causing these failures? Additionally, any suggestions or troubleshooting steps to resolve this issue would be highly appreciated.

Please let us know if you require any additional information from our end to assist in diagnosing and resolving this issue.

Thank you for your support.

**Comment by parvez-geokey** [comment]
Any update on above issue?

**Comment by parvez-geokey** [comment]
> We are currently experiencing significant failures with the unlock operations using your SDK in our iOS and Android applications. Below are the details:
> 
> iOS TTLock SDK Version: 3.3.11 Android TTLock SDK Version: 3.2.6
> 
> **Issue:**
> 
> Over the past two months, we have observed a substantial increase in the failure rate of unlock operations for some of our live users. For certain users, the failure rate exceeds 90%. Initially, we did not encounter such high failure rates.
> 
> **Key Points:**
> 
> * Occurrence: The issue has been observed for the past three months.
> * Failure Rate: Some users are experiencing more than 90% failure in unlock operations.
> * Reproducibility: It is reproduced on Android.
> * Operations Affected: Unlock operations specifically.
> * Functions Used: Lock, unlock, generate pincodes, read battery, etc.
> * Error: As we checked logs, in most cases we are getting "Connection timeout" and "lock is busy" errors from the SDK. The issue mostly occurs after we enable and disable mobile WiFi.
> * Device: The issue mostly occurs in the TTLock Bluetooth device.
> 
> We have not made any significant changes to our integration that could cause this issue. We are concerned that there might be changes or updates in the SDK or its dependencies that could be contributing to this problem.
> 
> **Request:**
> 
> Could you please investigate this matter and provide insights into any recent changes in the SDK versions mentioned that might be causing these failures? Additionally, any suggestions or troubleshooting steps to resolve this issue would be highly appreciated.
> 
> Please let us know if you require any additional information from our end to assist in diagnosing and resolving this issue.
> 
> Thank you for your support.

Any update on above issue?

**Comment by ttlock** [comment]
1 The SDK has not made any modifications in this regard.
2 Does the high failure rate you mentioned belong to a specific lock ？
3 Reproducibility: It is reproduced on Android.  How was it reproduced ？

**Comment by parvez-geokey** [comment]
> 1 The SDK has not made any modifications in this regard. 2 Does the high failure rate you mentioned belong to a specific lock ？ 3 Reproducibility: It is reproduced on Android. How was it reproduced ？

It has been fixed.
