### ISSUE TITLE
Signing Certificate for “TTLock.xcframework” Revoked – Unable to Build Project

### ISSUE THREAD

**Issue by davemccollough-geokey** [ttlock/iOS_SDK_Demo#42]
We are currently experiencing an issue where the signing certificate for the “TTLock.xcframework” appears to have been revoked, causing the following error when building our project:

```
Error: "The signature of 'TTLock.xcframework' cannot be validated and may have been compromised."
Cause: The signing certificate has been revoked.
```

This issue is blocking us from successfully building the project, as we rely on the TTLock SDK for our application. Please find the attached screenshots illustrating the error.
![Screenshot 2024-10-08 at 2 00 46 PM](https://github.com/user-attachments/assets/5d4af7d4-812e-40f2-9b06-e68d9508c1ce)

![Screenshot 2024-10-08 at 2 00 33 PM](https://github.com/user-attachments/assets/5b470a07-48b5-4efa-b7ee-535116a9efaa)

![Screenshot 2024-10-08 at 2 00 08 PM](https://github.com/user-attachments/assets/a226dd99-9c6e-4d04-bf7d-05b8e4384ef0)

Can you confirm if the certificate has indeed been revoked?

Your prompt assistance would be greatly appreciated, as it is currently impacting our development process.

Thank you for your time and support.

**Comment by ttlock** [comment]
[TTLock.xcframework.zip](https://github.com/user-attachments/files/17292387/TTLock.xcframework.zip)
Thank you , we will update sdks tomorrow. You can use this temporary one first.

**Comment by davemccollough-geokey** [comment]
> [TTLock.xcframework.zip](https://github.com/user-attachments/files/17292387/TTLock.xcframework.zip) Thank you , we will update sdks tomorrow. You can use this temporary one first.

Thank you for your prompt response and for providing the temporary zip file. We appreciate your assistance in addressing this issue.

We will proceed with the temporary SDK for now and look forward to the updated SDK tomorrow.

Thanks again for your support.

**Comment by parvez-geokey** [comment]
> [TTLock.xcframework.zip](https://github.com/user-attachments/files/17292387/TTLock.xcframework.zip) Thank you , we will update sdks tomorrow. You can use this temporary one first.

Additionally, we are encountering the same issue with TTLockWatchOS.xcframework. Could you please provide a solution for this framework as well?

**Comment by ttlock** [comment]
TTLockWatchOS.xcframework had updated.
