### ISSUE TITLE
touch to unlock

### ISSUE THREAD

**Issue by ahmedalttai** [ttlock/iOS_SDK_Demo#6]
Hello,

how to unable touch to unlock as same in TTlock app.

**Comment by JuannyiOS** [comment]
Hello,

such as, In method "startScan"&nbsp;TTScanBlock, when "isAllowTouchUnlock" == NO,do not to connect lock;if yes, to connect the lock."isAllowTouchUnlock"&nbsp;is the flag you set.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月13日(星期天) 晚上8:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] touch to unlock (#6)





 
Hello,
 
how to unable touch to unlock as same in TTlock app.

**Comment by ahmedalttai** [comment]
> Hello, such as, In method "startScan"&nbsp;TTScanBlock, when "isAllowTouchUnlock" == NO,do not to connect lock;if yes, to connect the lock."isAllowTouchUnlock"&nbsp;is the flag you set.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ttlock/iOS_SDK_Demo" ***@***.***&gt;; 发送时间:&nbsp;2021年6月13日(星期天) 晚上8:44 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ttlock/iOS_SDK_Demo] touch to unlock (#6) Hello, how to unable touch to unlock as same in TTlock app. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

There is no "isAllowTouchUnlock" flag in TTScanBlock, it only contain this:

TTLock.startScan({ (scanModel:TTScanModel!) in
            scanModel.isAllowUnlock
        })

**Comment by JuannyiOS** [comment]
Sorry, this has been a long time, I don't know if you have solved it or not.
isAllowTouchUnlock is not returned in the startScan method, it is a global setting.
scanModel.isAllowUnlock == YES && isAllowTouchUnlock == YES ,then connect lock,unlock.
