### ISSUE TITLE
XCFramework Support

### ISSUE THREAD

**Issue by kelvin-lima** [ttlock/iOS_SDK_Demo#7]
Do you have plans to make available a version of TTLock Frameworks as XCFrameworks to avoid compilation problems on M1 Macs and Xcode 12+?

I'm currently facing some issues as you can see above.

![image](https://user-images.githubusercontent.com/3374682/127203555-db4a1741-6e44-433c-80f9-b9aa2146b396.png)

Additionally, I'm interested to use SDK at watchOS but I cannot find any information about them. Do they exist?

E-mail: kelvin@loopkey.com.br

**Comment by JuannyiOS** [comment]
We need some time to adapt XCFrameworks. If ok,we will send email to you.
You need to adapt the current sdk first if there are mistakes.&nbsp;
The SDK of the watchOS has been passed on github :https://github.com/ttlock/watchOS_SDK


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 凌晨1:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] XCFramework Support (#7)





 
Do you have plans to make available a version of TTLock Frameworks as XCFrameworks to avoid compilation problems on M1 Macs and Xcode 12+?
 
I'm currently facing some issues as you can see above.
 

 
Additionally, I'm interested to use SDK at watchOS but I cannot find any information about them. Do they exist?
 
E-mail: ***@***.***

**Comment by kelvin-lima** [comment]
Send an e-mail please :).
Thanks for the Answer.

**Comment by kelvin-lima** [comment]
Your project is Swift compatible? I'm trying to import your code but the compiler report "Module not found". Do you have any integration guide to make it work with Swift?

**Comment by JuannyiOS** [comment]
SDK updated:https://github.com/ttlock/watchOS_SDK please try again



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月28日(星期三) 晚上7:51
收件人: "ttlock/iOS_SDK_Demo";
抄送: "Comment";
主题: Re: [ttlock/iOS_SDK_Demo] XCFramework Support (#7)





 
Send an e-mail please :).
 Thanks for the Answer.
 
&mdash;

**Comment by pathanparvezkhan** [comment]
Any update on Xcframework support?

**Comment by JuannyiOS** [comment]
Sorry, not yet

**Comment by JuannyiOS** [comment]
Updated xcframework  , version 3.3.0
